"""Source-native HubSpot fixed routes; no arbitrary URL or policy decisions."""

HUBSPOT_ACTION_SPECS = {
    "crm.contacts.get": {
        "method": "GET",
        "path": "/crm/objects/2026-03/contacts/{contact_id}",
        "body_field": None,
        "has_body": False,
        "query": True,
        "write": False,
    },
    "bulk.exports.create": {
        "method": "POST",
        "path": "/crm/exports/2026-03/export/async",
        "body_field": None,
        "has_body": True,
        "query": False,
        "write": True,
    },
    "bulk.exports.status": {
        "method": "GET",
        "path": "/crm/exports/2026-03/export/{job_id}",
        "body_field": None,
        "has_body": False,
        "query": True,
        "write": False,
    },
    "bulk.exports.result": {
        "method": "GET",
        "path": "/crm/exports/2026-03/export/async/tasks/{job_id}/status",
        "body_field": None,
        "has_body": False,
        "query": True,
        "write": False,
    },
    "crm.contacts.properties.list": {
        "method": "GET",
        "path": "/crm/properties/2026-03/contacts",
        "body_field": None,
        "has_body": False,
        "query": True,
        "write": False,
    },
    "crm.companies.properties.list": {
        "method": "GET",
        "path": "/crm/properties/2026-03/companies",
        "body_field": None,
        "has_body": False,
        "query": True,
        "write": False,
    },
    "crm.deals.properties.list": {
        "method": "GET",
        "path": "/crm/properties/2026-03/deals",
        "body_field": None,
        "has_body": False,
        "query": True,
        "write": False,
    },
    "crm.leads.properties.list": {
        "method": "GET",
        "path": "/crm/properties/2026-03/leads",
        "body_field": None,
        "has_body": False,
        "query": True,
        "write": False,
    },
    "sales.products.properties.list": {
        "method": "GET",
        "path": "/crm/properties/2026-03/products",
        "body_field": None,
        "has_body": False,
        "query": True,
        "write": False,
    },
    "sales.line_items.properties.list": {
        "method": "GET",
        "path": "/crm/properties/2026-03/line_items",
        "body_field": None,
        "has_body": False,
        "query": True,
        "write": False,
    },
    "sales.quotes.properties.list": {
        "method": "GET",
        "path": "/crm/properties/2026-03/quotes",
        "body_field": None,
        "has_body": False,
        "query": True,
        "write": False,
    },
    "sales.goal_targets.properties.list": {
        "method": "GET",
        "path": "/crm/properties/2026-03/goal_targets",
        "body_field": None,
        "has_body": False,
        "query": True,
        "write": False,
    },
    "crm.owners.list": {
        "method": "GET",
        "path": "/crm/owners/2026-03",
        "body_field": None,
        "has_body": False,
        "query": True,
        "write": False,
    },
    "crm.deals.pipelines.list": {
        "method": "GET",
        "path": "/crm/pipelines/2026-03/deals",
        "body_field": None,
        "has_body": False,
        "query": True,
        "write": False,
    },
    "crm.contact_company.labels.list": {
        "method": "GET",
        "path": "/crm/associations/2026-03/contacts/companies/labels",
        "body_field": None,
        "has_body": False,
        "query": True,
        "write": False,
    },
    "crm.contact_deal.labels.list": {
        "method": "GET",
        "path": "/crm/associations/2026-03/contacts/deals/labels",
        "body_field": None,
        "has_body": False,
        "query": True,
        "write": False,
    },
    "crm.company_deal.labels.list": {
        "method": "GET",
        "path": "/crm/associations/2026-03/companies/deals/labels",
        "body_field": None,
        "has_body": False,
        "query": True,
        "write": False,
    },
    "crm.contact_company.associate": {
        "method": "PUT",
        "path": "/crm/objects/2026-03/contact/{from_id}/associations/company/{to_id}",
        "body_field": "types",
        "has_body": True,
        "query": False,
        "write": True,
    },
    "crm.contact_deal.associate": {
        "method": "PUT",
        "path": "/crm/objects/2026-03/contact/{from_id}/associations/deal/{to_id}",
        "body_field": "types",
        "has_body": True,
        "query": False,
        "write": True,
    },
    "crm.company_deal.associate": {
        "method": "PUT",
        "path": "/crm/objects/2026-03/company/{from_id}/associations/deal/{to_id}",
        "body_field": "types",
        "has_body": True,
        "query": False,
        "write": True,
    },
    "crm.contact_company.dissociate": {
        "method": "POST",
        "path": "/crm/associations/2026-03/contacts/companies/batch/labels/archive",
        "body_field": None,
        "has_body": True,
        "query": False,
        "write": True,
    },
    "crm.contact_deal.dissociate": {
        "method": "POST",
        "path": "/crm/associations/2026-03/contacts/deals/batch/labels/archive",
        "body_field": None,
        "has_body": True,
        "query": False,
        "write": True,
    },
    "crm.company_deal.dissociate": {
        "method": "POST",
        "path": "/crm/associations/2026-03/companies/deals/batch/labels/archive",
        "body_field": None,
        "has_body": True,
        "query": False,
        "write": True,
    },
    "sales.line_items.associate_deal": {
        "method": "PUT",
        "path": (
            "/crm/objects/2026-03/line_items/{line_item_id}/associations/default/deals/{deal_id}"
        ),
        "body_field": None,
        "has_body": False,
        "query": False,
        "write": True,
    },
    "sales.line_items.dissociate_deal": {
        "method": "DELETE",
        "path": "/crm/objects/2026-03/line_items/{line_item_id}/associations/deals/{deal_id}",
        "body_field": None,
        "has_body": False,
        "query": False,
        "write": True,
    },
    "crm.companies.batch_upsert": {
        "method": "POST",
        "path": "/crm/objects/2026-03/companies/batch/upsert",
        "body_field": None,
        "has_body": True,
        "query": False,
        "write": True,
    },
    "crm.contacts.batch_upsert": {
        "method": "POST",
        "path": "/crm/objects/2026-03/contacts/batch/upsert",
        "body_field": None,
        "has_body": True,
        "query": False,
        "write": True,
    },
    "crm.deals.batch_upsert": {
        "method": "POST",
        "path": "/crm/objects/2026-03/deals/batch/upsert",
        "body_field": None,
        "has_body": True,
        "query": False,
        "write": True,
    },
    "crm.leads.batch_upsert": {
        "method": "POST",
        "path": "/crm/objects/2026-03/leads/batch/upsert",
        "body_field": None,
        "has_body": True,
        "query": False,
        "write": True,
    },
    "sales.products.batch_upsert": {
        "method": "POST",
        "path": "/crm/objects/2026-03/products/batch/upsert",
        "body_field": None,
        "has_body": True,
        "query": False,
        "write": True,
    },
    "sales.line_items.batch_upsert": {
        "method": "POST",
        "path": "/crm/objects/2026-03/line_items/batch/upsert",
        "body_field": None,
        "has_body": True,
        "query": False,
        "write": True,
    },
    "crm.notes.create": {
        "method": "POST",
        "path": "/crm/objects/2026-03/notes",
        "body_field": None,
        "has_body": True,
        "query": False,
        "write": True,
    },
    "crm.tasks.create": {
        "method": "POST",
        "path": "/crm/objects/2026-03/tasks",
        "body_field": None,
        "has_body": True,
        "query": False,
        "write": True,
    },
    "crm.calls.create": {
        "method": "POST",
        "path": "/crm/objects/2026-03/calls",
        "body_field": None,
        "has_body": True,
        "query": False,
        "write": True,
    },
    "crm.meetings.create": {
        "method": "POST",
        "path": "/crm/objects/2026-03/meetings",
        "body_field": None,
        "has_body": True,
        "query": False,
        "write": True,
    },
    "crm.contacts.search": {
        "method": "POST",
        "path": "/crm/objects/2026-03/contacts/search",
        "body_field": None,
        "has_body": True,
        "query": False,
        "write": False,
    },
    "crm.companies.search": {
        "method": "POST",
        "path": "/crm/objects/2026-03/companies/search",
        "body_field": None,
        "has_body": True,
        "query": False,
        "write": False,
    },
    "crm.deals.search": {
        "method": "POST",
        "path": "/crm/objects/2026-03/deals/search",
        "body_field": None,
        "has_body": True,
        "query": False,
        "write": False,
    },
    "crm.leads.search": {
        "method": "POST",
        "path": "/crm/objects/2026-03/leads/search",
        "body_field": None,
        "has_body": True,
        "query": False,
        "write": False,
    },
    "sales.products.search": {
        "method": "POST",
        "path": "/crm/objects/2026-03/products/search",
        "body_field": None,
        "has_body": True,
        "query": False,
        "write": False,
    },
    "sales.line_items.search": {
        "method": "POST",
        "path": "/crm/objects/2026-03/line_items/search",
        "body_field": None,
        "has_body": True,
        "query": False,
        "write": False,
    },
    "sales.quotes.search": {
        "method": "POST",
        "path": "/crm/objects/2026-03/quotes/search",
        "body_field": None,
        "has_body": True,
        "query": False,
        "write": False,
    },
    "sales.goal_targets.list": {
        "method": "GET",
        "path": "/crm/objects/2026-03/goal_targets",
        "body_field": None,
        "has_body": False,
        "query": True,
        "write": False,
    },
    "marketing.forms.list": {
        "method": "GET",
        "path": "/marketing/v3/forms",
        "body_field": None,
        "has_body": False,
        "query": True,
        "write": False,
    },
    "marketing.forms.submissions.list": {
        "method": "GET",
        "path": "/form-integrations/v1/submissions/forms/{form_id}",
        "body_field": None,
        "has_body": False,
        "query": True,
        "write": False,
    },
    "marketing.segments.list": {
        "method": "POST",
        "path": "/crm/lists/2026-03/search",
        "body_field": None,
        "has_body": True,
        "query": False,
        "write": False,
    },
    "marketing.segments.memberships.list": {
        "method": "GET",
        "path": "/crm/lists/2026-03/{segment_id}/memberships",
        "body_field": None,
        "has_body": False,
        "query": True,
        "write": False,
    },
    "marketing.segments.memberships.add": {
        "method": "PUT",
        "path": "/crm/lists/2026-03/{segment_id}/memberships/add",
        "body_field": "ids",
        "has_body": True,
        "query": False,
        "write": True,
    },
    "marketing.segments.memberships.remove": {
        "method": "PUT",
        "path": "/crm/lists/2026-03/{segment_id}/memberships/remove",
        "body_field": "ids",
        "has_body": True,
        "query": False,
        "write": True,
    },
    "marketing.campaigns.list": {
        "method": "GET",
        "path": "/marketing/campaigns/2026-03",
        "body_field": None,
        "has_body": False,
        "query": True,
        "write": False,
    },
    "marketing.campaigns.get": {
        "method": "GET",
        "path": "/marketing/campaigns/2026-03/{campaign_id}",
        "body_field": None,
        "has_body": False,
        "query": True,
        "write": False,
    },
    "marketing.campaigns.create": {
        "method": "POST",
        "path": "/marketing/campaigns/2026-03",
        "body_field": None,
        "has_body": True,
        "query": False,
        "write": True,
    },
    "marketing.campaigns.update": {
        "method": "PATCH",
        "path": "/marketing/campaigns/2026-03/{campaign_id}",
        "body_field": None,
        "has_body": True,
        "query": False,
        "write": True,
    },
    "marketing.emails.list": {
        "method": "GET",
        "path": "/marketing/emails/2026-03",
        "body_field": None,
        "has_body": False,
        "query": True,
        "write": False,
    },
    "marketing.emails.get": {
        "method": "GET",
        "path": "/marketing/emails/2026-03/{email_id}",
        "body_field": None,
        "has_body": False,
        "query": True,
        "write": False,
    },
    "marketing.emails.create": {
        "method": "POST",
        "path": "/marketing/emails/2026-03",
        "body_field": None,
        "has_body": True,
        "query": False,
        "write": True,
    },
    "marketing.emails.update": {
        "method": "PATCH",
        "path": "/marketing/emails/2026-03/{email_id}",
        "body_field": None,
        "has_body": True,
        "query": False,
        "write": True,
    },
    "transactional.single_email.send": {
        "method": "POST",
        "path": "/marketing/transactional/2026-03/single-email/send",
        "body_field": None,
        "has_body": True,
        "query": False,
        "write": True,
    },
    "marketing.subscription_types.list": {
        "method": "GET",
        "path": "/communication-preferences/2026-03/definitions",
        "body_field": None,
        "has_body": False,
        "query": True,
        "write": False,
    },
    "marketing.contact_preferences.get": {
        "method": "GET",
        "path": "/communication-preferences/2026-03/statuses/{email}",
        "body_field": None,
        "has_body": False,
        "query": True,
        "write": False,
    },
    "marketing.contact_preferences.update": {
        "method": "POST",
        "path": "/communication-preferences/2026-03/statuses/{email}",
        "body_field": None,
        "has_body": True,
        "query": False,
        "write": True,
    },
    "marketing.events.list": {
        "method": "GET",
        "path": "/marketing/marketing-events/2026-03",
        "body_field": None,
        "has_body": False,
        "query": True,
        "write": False,
    },
    "marketing.events.upsert": {
        "method": "POST",
        "path": "/marketing/marketing-events/2026-03/events/upsert",
        "body_field": None,
        "has_body": True,
        "query": False,
        "write": True,
    },
    "marketing.behavioral_events.definitions.list": {
        "method": "GET",
        "path": "/events/2026-03/event-definitions",
        "body_field": None,
        "has_body": False,
        "query": True,
        "write": False,
    },
    "marketing.behavioral_events.send": {
        "method": "POST",
        "path": "/events/2026-03/send",
        "body_field": None,
        "has_body": True,
        "query": False,
        "write": True,
    },
    "crm.deals.list": {
        "method": "GET",
        "path": "/crm/objects/2026-03/deals",
        "body_field": None,
        "has_body": False,
        "query": True,
        "write": False,
    },
}
