query LinearIssueLabelsList(
  $filter: IssueLabelFilter
  $first: Int!
  $after: String
  $includeArchived: Boolean
  $orderBy: PaginationOrderBy
) {
  issueLabels(
    filter: $filter
    first: $first
    after: $after
    includeArchived: $includeArchived
    orderBy: $orderBy
  ) {
    nodes {
      id
      name
      description
      color
      isGroup
      archivedAt
      team {
        id
        name
        key
      }
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
